/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RenovaCommandDeck } from "./RenovaCommandDeck";
export type { RenovaCommandDeckBase } from "./RenovaCommandDeckBase";
export type { RenovaCommandDeckSatellite } from "./RenovaCommandDeckSatellite";
export type { RenovaQuest } from "./RenovaQuest";
