/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC721RoyaltyUpgradeable__factory } from "./ERC721RoyaltyUpgradeable__factory";
export { IERC721MetadataUpgradeable__factory } from "./IERC721MetadataUpgradeable__factory";
