/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDaiLikePermit } from "./IDaiLikePermit";
export type { IPermit2 } from "./IPermit2";
export type { IWETH } from "./IWETH";
