/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ContractOnlyEthRecipient,
  ContractOnlyEthRecipientInterface,
} from "../../../contracts/features/ContractOnlyEthRecipient";

const _abi = [
  {
    inputs: [],
    name: "DirectEthDepositIsForbidden",
    type: "error",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class ContractOnlyEthRecipient__factory {
  static readonly abi = _abi;
  static createInterface(): ContractOnlyEthRecipientInterface {
    return new Interface(_abi) as ContractOnlyEthRecipientInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ContractOnlyEthRecipient {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ContractOnlyEthRecipient;
  }
}
