/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { RenovaAvatar__factory } from "./RenovaAvatar__factory";
export { RenovaAvatarBase__factory } from "./RenovaAvatarBase__factory";
export { RenovaAvatarSatellite__factory } from "./RenovaAvatarSatellite__factory";
export { RenovaItem__factory } from "./RenovaItem__factory";
export { RenovaItemBase__factory } from "./RenovaItemBase__factory";
export { RenovaItemSatellite__factory } from "./RenovaItemSatellite__factory";
